[SAP] Mark a pool as down if overcommited
sapcc/cinder pull request #141
Opened 2022-09-07 20:07 UTC by hemna

This patch will check the capacity factors of a pool and check it's virtual_free_capacity left every time the volume manager gets the volume stats from the backend.  If the virtual_free_capacity is <= 0 then the pool is overcommited and will be marked down.

The new SAPPoolDownFilter will check against this pool_state and if it's down, then filter the pool out of results for the scheduler.

This patch also updates the vmware driver to properly report the thin/thick capability depending on the volume type's provisioning:type setting.  This is used to determine the proper capacity factors for the provisioning type.

2022-09-22 11:09 UTC, joker-at-work requested changes
Usually, scheduler filters are an easy grab for a test as they get pretty well-defined input and have well-defined output. That way, we can define the exact behavior we expect from the filter in a little more details. That test would have probably also noticed the bug ;)

2022-09-23 13:56 UTC, hemna commented on cinder/scheduler/filters/sap_pool_down_filter.py
> +CONF = cfg.CONF
done

2022-09-23 14:03 UTC, hemna commented on cinder/scheduler/filters/sap_pool_down_filter.py
> +                  {'state': backend_state})
fixed.

2022-09-23 15:27 UTC, hemna commented on cinder/volume/drivers/vmware/vmdk.py
> +        return None
done

2022-09-26 13:54 UTC, joker-at-work reviewed
Looks good otherwise.

2022-09-26 13:54 UTC, joker-at-work commented on cinder/scheduler/filters/sap_pool_down_filter.py
> +            LOG.debug("%(id)s pool state is not 'up'.  state='%(state)s'",
nitpick: double spaces before `state=`.

2022-09-26 13:54 UTC, joker-at-work commented on cinder/scheduler/filters/sap_pool_down_filter.py
> +    """Filter out pools that are marked 'down'."""
Current implementation is `that are not marked 'up'`

2022-09-27 12:10 UTC, merged