[SAP] Change default provisioning type in vmdk
sapcc/cinder pull request #213
Opened 2024-10-08 13:43 UTC by hemna

This patch changes the default provisioning type in the vmdk driver to thick, since we use thick everywhere for vmware/fcd based volumes.  This allows us to remove the volume type extra specs setting.

2024-10-08 13:59 UTC, joker-at-work commented
Test failed.

2024-10-09 07:16 UTC, joker-at-work approved these changes

2024-10-09 10:28 UTC, grandchild requested changes

2024-10-09 10:28 UTC, grandchild commented on cinder/volume/drivers/vmware/vmdk.py
>          """
The comment doesn't match the function anymore

2024-10-09 10:32 UTC, grandchild commented on cinder/volume/drivers/vmware/vmdk.py
>          """
(one could argue to remove the whole line from the doc comment, since it's spelled out very clearly in the 3-line function body)

2024-10-09 13:36 UTC, joker-at-work approved these changes

2024-10-15 12:43 UTC, grandchild approved these changes

2024-10-15 13:17 UTC, merged